name: Hello Github Actions

on:

  push:
	branches:
     -main
jobs:
  say-hello:
   run-on: ubuntu-lastet
	steps:
	  -name: Exibir mensagem no log
	   run: echo " Github Action funcionando com sucesso!"
